name: zaoed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dashed_stepper: ^0.0.4
  easy_stepper: ^0.8.3
  fl_chart: ^0.66.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  glass: ^1.0.2+1
  intl: ^0.18.1
  image_picker: ^1.0.5
  lottie: ^2.7.0
  pinput: ^3.0.1
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.0.2
  syncfusion_flutter_charts: ^24.1.41
  syncfusion_flutter_gauges: ^24.1.41
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  google_maps_flutter: ^2.5.0
  image: ^4.1.3
  moyasar: ^2.0.5
  flutter_credit_card: ^4.0.1
  webview_flutter: ^4.4.2
  qr_code_scanner: ^1.0.1
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets//lottie/
    - lib/assets/google_map_style/
  fonts:
    - family: SfArabic
      fonts:
        - asset: fonts/SFArabic-Regular.ttf
