name: zaoed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dashed_stepper: ^0.0.4
  easy_stepper: ^0.8.3
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  glass: ^2.0.0+1
  intl: ^0.19.0
  image_picker: ^1.0.5
  lottie: ^3.1.2
  pinput: ^5.0.0
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^2.0.2
  syncfusion_flutter_charts: ^26.1.42
  syncfusion_flutter_gauges: ^26.1.42
  flutter_polyline_points: ^2.0.0
  location: ^6.0.2
  google_maps_flutter: ^2.5.0
  image: ^4.1.3
  moyasar: ^2.0.5
  flutter_credit_card: ^4.0.1
  webview_flutter: ^4.4.2
  qr_code_scanner: ^1.0.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/
  fonts:
    - family: SfArabic
      fonts:
        - asset: fonts/SFArabic-Regular.ttf
